### PR TITLE
AdvancedChests hook bug fixed!

### PR DESCRIPTION
**Pull request by DeadSilenceIV**
Hello i just wanted to fix a small bug related to the hook of my plugin AdvancedChests.

### CODE REVIEW

**Comment by mfnalex** [comment]
Thanks, will merge tomorrow (still on vacation)

**Comment by mfnalex** [comment]
Is the check whether AE is installed not needed? Oh and what was the bug? I need to know for the changelog :)

**Comment by DeadSilenceIV** [comment]
1. Yes, the verification is still required.
2. The thing is that previously i was using a method that gets the AdvancedChests if the passed inventory is part of the chest, however, since i only want the main inventory of the chest(The ChestPage class) to be sorted, i added an extra check to see if the passed inventory is a ChestPage and not another sub-inventory of the chest.

**Comment by DeadSilenceIV** [comment]
Hello, it seems that the fix of this problem haven't been posted correctly on the lastest spigot update because the jar seems to contain the old code, i would really appreciate if you could verify it thanks.

**Comment by mfnalex** [comment]
whoops sorry, no idea how that could have happened. will reupload it now

**Pull request merged**
