### PR TITLE
AdvancedChests support

### PR DESCRIPTION
**Pull request by DeadSilenceIV**
Hello :smile:, i added support for my plugin [AdvancedChests](https://www.spigotmc.org/resources/%E2%AD%90advancedchests%E2%AD%90-unlimited-sizes-holograms-%E2%9C%A8upgrades-%E2%9C%85sells-%E2%9A%A1sorter-%E2%98%84%EF%B8%8F-compressor.79061/) and did some small corrections to the code that i hope help to the project.

### CODE REVIEW

**Comment by Bloodlex** [comment]
Thanks a lot! 🙂 👍

**Comment by mfnalex** [comment]
Thank you very much, will check out in a few hours and then merge & release :)

**Comment by mfnalex** [comment]
@Bloodlex I assume you tested this, and didn't encounter any problems, right?

**Comment by DeadSilenceIV** [comment]
Yes i did and it worked perfectly!

**Comment by mfnalex** [comment]
Okay thanks :)

**Pull request merged**
