### PR TITLE
AdvancedChests hook was updated and it now supports outside hotkeys.

### PR DESCRIPTION
**Pull request by DeadSilenceIV**
This pull request adds support for the latest API version of AdvancedChests and enable some missing inventory hotkeys.

### CODE REVIEW

**Comment by mfnalex** [comment]
Thanks! Did you test whether everything works fine? If so I'll merge it today or tomorrow, then release it on SpigotMC

**Comment by DeadSilenceIV** [comment]
Yes, i tested it and it was working fine.

**Comment by mfnalex** [comment]
Thanks. Please lemme know your SpigotMC username so I can thank you in the Spigot changelog when uploading the update.

**Comment by DeadSilenceIV** [comment]
https://www.spigotmc.org/members/deadsilenceiv.135601/

**Pull request merged**
